### ISSUE TITLE
[Reactive] Navigation breaks internal Refresh command of feeds on Android and IOS

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#1109]
## Current behavior
![doesnotreload](https://user-images.githubusercontent.com/90481654/214567157-278c72a1-33bc-4331-8095-54d352bb4379.gif)

So, there's two things that I've noticed don't work properly. 

1:  On IOS, in a freshly opened app, when you press on reload, the reload works the first time but it seems like the command never finishes executing the first time you press on it.

2: On Android and IOS : If you navigate to another page and back, then the internal refresh of the FeedView does not work. If you press on refresh, the command seems to just start executing and then it doesnt work. 

I guess it's important to note that before I made the sample, I only noticed the second bug happening on IOS, and the first bug is something I've never noticed. 

## Expected behavior
![Refresh works](https://user-images.githubusercontent.com/90481654/214567621-c8610ee9-28d3-4de8-90cb-f80d16add6ea.gif)

The internal refresh command should just work, always, like it does on WInUI

## How to reproduce it (as minimally and precisely as possible)
Open sample with this in the mainpage. On android, notice that the refresh works well at first, but after navigation, it stops working.

On IOS, notice that the first refresh refreshes the data, but then it gets stuck there. After navigating, it just doesnt work.

In xaml: 
```
 <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <Button Content="Navigate next page" Click="Button_Click1" HorizontalAlignment="Center" VerticalAlignment="Center"/>


        <uer:FeedView x:Name="MainFeedView"
                      Source="{Binding Test}"
                      Style="{StaticResource DefaultFeedViewStyle}"
                      Grid.Row="1">
            <DataTemplate>
                <StackPanel>
                    <TextBlock Text="{Binding Data}" Margin="20" FontSize="30" />
                    <Button Command="{Binding Refresh}" VerticalAlignment="Center" Content="Refresh"/>

                </StackPanel>
            </DataTemplate>
        </uer:FeedView>
    </Grid>
```
In CodeBehind
```
public IFeed<string> Test => Feed.Async(GetStrings);

        private void Button_Click1(object sender, RoutedEventArgs e)
        {
            App.RootFrame.Navigate(typeof(BlankPage1));
        }

        public MainPage()
        {
            this.InitializeComponent();
            DataContext = this;

        }

        private int _refreshedCounter = 0;

        public async ValueTask<string> GetStrings(CancellationToken ct)
        {
            return $"Refreshed : {_refreshedCounter++}";
        }
```

[BrokenFeedRefresh.zip](https://github.com/unoplatform/uno.extensions/files/10499544/BrokenFeedRefresh.zip)

## Environment

Nuget Package:

Uno.Extensions.Reactive

Package Version(s):
```
    <PackageReference Include="Uno.Extensions.Reactive" Version="2.3.0-dev.536" />
    <PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.3.0-dev.536" />
    <PackageReference Include="Uno.WinUI" Version="4.8.0-dev.6" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.8.0-dev.6" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.39" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.8.0-dev.6" />
```
Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
The IOS refresh not working after navigation is the only part that we can see in the app where we got this bug in the first place.

**Comment by nickrandolph** [comment]
Two things:
- The fix is to apply the NavigationCacheMode="Required" attribute to MainPage - this prevents page from being recreated which does indeed break feeds
- The above point isn't quite enough because of what must be a bug in the default frame presenter in Uno. If you add reference to the toolkit (package ref and add resources in app.xaml) and apply the above fix, you should see that the Refresh button continues to work 

cc @kazo0 can you try this sample and see if you can work out why setting cache mode to required doesn't work without adding reference to toolkit?

**Comment by kazo0** [comment]
The Toolkit sets the Frame's style to use the Toolkit's `NativeFramePresenter` by default. Without Toolkit, you need to explicitly set up the Frame to use Uno's `NativeFramePresenter` by setting   `Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation()`

If that doesn't work, maybe we fixed something in Toolkit but forgot to implement the fix in the Uno `NativeFramePresenter`?

**Comment by Marc-Antoine-Soucy** [comment]
So, addding 'Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation();' in App.xaml.cs and             'NavigationCacheMode = NavigationCacheMode.Required;' in the mainpage.xaml.cs did fix the bug for android did fix the issue for android. That also explains why we didnt have this bug in the main app for android. It did not fix any of the bugs for IOS, however. Should I remove android from the title?

**Comment by kazo0** [comment]
Ok, so this is where things get weird. There is nothing in Uno or Toolkit that uses the `NavigationCacheMode` property of `Page`. Perhaps it's being used by something in Extensions? I do see some caching logic within the managed Frame logic but it is behind a Feature Flag `IsPoolingEnabled` and it looks to only be [caching any pages in the ForwardStack when a Navigation with mode == New is performed](https://github.com/unoplatform/uno/blob/a8e9071ba5dbe7233ed054ae8dfe1fba6b67f1b6/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs#L342-L346)

My thought here is that we could instead be checking the `NavigationCacheMode` of the `Page` when they get created from [here](https://github.com/unoplatform/uno/blob/a8e9071ba5dbe7233ed054ae8dfe1fba6b67f1b6/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs#L350), and then cache them accordingly, no?

The `NativeFramePresenter`s, both in Uno and Toolkit, already have logic to [reuse the inactive pages on Android](https://github.com/unoplatform/uno/blob/a911ec8288090db0cf3fd0c6a8815c612e531ab7/src/Uno.UI/NativeFramePresenter.Android.cs#L150). This logic is enabled by default but can be disabled by setting the feature flag `FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages` to `false`. So, if you were to set `Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation()` and `FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages = false`, you would then continue to experience the bug from this issue. But simply setting `Uno.UI.FeatureConfiguration.Style.ConfigureNativeFrameNavigation()` alone will properly use the cached pages.

I can't seem to find a path where this would work on iOS. The `NativeFramePresenter`s doesn't seem to have any specific logic surrounding caching of inactive pages. No matter if I use the Toolkit or Uno's `NativeFramePresenter`, or the managed `Frame` logic, or any combination with `NavigationCacheMode`, I would always see the Feeds bug,

**Comment by nickrandolph** [comment]
This has been fixed with updates to toolkit and uno
