### ISSUE TITLE
[MVU] Changing theme takes too long, ItemsRepeater seems to not dispose items

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.extensions#2428]
### Discussed in https://github.com/unoplatform/uno.extensions/discussions/2395

<div type='discussions-op-text'>

<sup>Originally posted by **kucint** June 26, 2024</sup>
This one is tricky....

let's create a simple MVU model with the list state

```cs
internal record Item(string Text, Brush Brush);

internal partial record MainPageModel
{
    public IListState<Item> Items => ListState<Item>.Value(this, () =>
    [
        new Item("A", new SolidColorBrush(Colors.DeepSkyBlue)),
        new Item("B", new SolidColorBrush(Colors.DarkOrchid)),
    ]);
}
```

Let connect the list state to the view:

```cs
    new ScrollViewer()
    .Content(
        new ItemsRepeater()
        .ItemsSource(() => vm.Items)
        //.Layout(new StackLayout())            // this is virtualizing layout
        .Layout(new NonVirtualStackLayout())    // this is non-virtualizing layout
        .ItemTemplate<Item>(item => GetItemView(item))
        )

    private static Grid GetItemView(Item item) => new Grid().Children(
        new Rectangle()
        .Width(100)
        .Height(20)
        .Stroke(Colors.Black)
        .StrokeThickness(1)
        .Fill(Themes.MyBrush)      // themes binding
        .Margin(3),
        new TextBlock()
        .Text(() => item.Text)
        .VerticalAlignment(VerticalAlignment.Center)
        .HorizontalAlignment(HorizontalAlignment.Center)
        .Foreground(() => item.Brush)
        );
```
Please note the Themes binding used in the item

```cs
internal static class Themes
{
    public static readonly Resource<Brush> MyBrush = ThemeResource.Create<Brush>(nameof(MyBrush),
        new SolidColorBrush(Colors.LightBlue), new SolidColorBrush(Colors.LightCoral));
}
```

This app works like a charm with both virtualizing layout and non-virtualizing layout:

![image](https://github.com/unoplatform/uno.extensions/assets/54866088/a70a945d-63e2-4eb1-9e9f-1b8c6a9f3511)

The app allows to add more items to the list and switch the light/dark mode. All good.

**Issue 1**

When a number of the items grows, the time of theme switch takes surprisingly very long time: with 2000 items created it takes more then 10 sec (debug).
The long execution time is observed only on non-virtualizing layout. On virtualizing layout, the switch is quick (obviously)

**Issue 2**
if a significant number of items have been added (~2000) and then all of them are removed (items count is again 0) I would expect that the theme switch is again quick but this is not a case. it takes exactly the same amount of time as all 2000 items would still exist.

I do not understand why it so, but it seems to me, that somehow removed items still persist and influence the app.
No idea if it has something to do with `Themes`, `ItemsRepeater`, `MVU state update` or any combination of these.

If items remain indeed undisposed, this issue would be hidden when using any of virtualizing layout...

**Remarks**:
 - It is maybe obvious, but ..... if you comment out the theme binding line: `// .Fill(Themes.MyBrush)` than switching theme is again quick, so the issues have nothing to do with the number of items being rendered.
 - `NonVirtualStackLayout` class has been copied from uno unit tests: Uno.UI.RuntimeTests\MUX\Microsoft_UI_Xaml_Controls\Repeater\Common\NonVirtualStackLayout.cs 
so I assume it is rather not the cause of problems here...

repro: [UnoThemeTooSlowApp.zip](https://github.com/user-attachments/files/15986850/UnoThemeTooSlowApp.zip)

</div>

**Comment by dansiegel** [comment]
@kucint we've merged an update for this. Please give it a try and let us know if this resolves your issues.

**Comment by kucint** [comment]
Hi @dansiegel, 

testing on `"Uno.Sdk": "5.4.0-dev.145"` on `debug`

___
**Desktop**
**Results**: I do not observe any changes: **Issue 1** and **Issue 2** persist as before.
___
**Windows**
As the issue has been created, the app when run on windows thrown an exception. 
Now, thanks to some bug fixes, it is starting correctly and I can test how it behaves.

**Results**: Switching to dark mode takes infinite time (app hangs), even for 8 elements.

**Comment by kazo0** [comment]
@kucint Are you able to bump the `UnoCSharpMarkupVersion` in your `Directory.Build.props` to `5.4.0-dev.35` and see if that makes any difference?

**Comment by MartinZikmund** [comment]
@kucint the fix was released super recently, so the latest Uno.Sdk release does not include it yet - 

You need to have this version: https://www.nuget.org/packages/Uno.WinUI.Markup/5.4.0-dev.35

You should be able to do that via:

```xml
<UnoCSharpMarkupVersion>5.4.0-dev.35</UnoCSharpMarkupVersion>
```

Or wait for the next prerelease Uno.Sdk which will include it (but can't promise exactly when it goes out

**Comment by kucint** [comment]
sure. using `<UnoCSharpMarkupVersion>5.4.0-dev.35</UnoCSharpMarkupVersion>` now:

- **Desktop**: 
**Issue 1** and **Issue 2** solved! the theme change is quick, almost immediate. Well done!
- **Windows**: 
still crashing when trying to add elements to the collection
 _System.Runtime.InteropServices.COMException: ErrorCode -2147417842_

**Comment by MartinZikmund** [comment]
@kazo0 @dansiegel can you please check the Windows issue?

**Comment by kazo0** [comment]
FYI @MartinZikmund / @kucint 

I will create a separate issue for the Windows crash as it seems unrelated to the theme changing. Since the slowness has been fixed I will close this issue
