### ISSUE TITLE
[Auth] Use custom IBrowser for OIDC/MSAL

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.extensions#2640]
Use something similar to https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/main/NetCoreConsoleClient/src/NetCoreConsoleClient/SystemBrowser.cs for a browser implementation that can support net-desktop targets

I believe @carldebilly has a modified version of this that can do away with the Kestrel dependency.

**Comment by kazo0** [comment]
Poking @carldebilly / @nickrandolph for anymore info that we need for this one. 

Doing this will allow us to no longer rely on the `WebAuthenticationBroker`, correct?

**Comment by carldebilly** [comment]
Yep. Actually I did something slightly different: instead of customizing the IBrowser which is specific to EntityModel.OidcClient (now renamed `Duende.IdentityModel.OidcClient`), I implemented something registering a custom WebAuthenticationBroker into Uno (using api extensibility mechanisms built into Uno) and used the [AutoRedirectUri](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationSettings.cs#L10) feature to correctly resolve the uri from the browser.

The missing piece is the custom WAB, which is using [my "new" http server](https://github.com/carldebilly/Yllibed.HttpServer) which is extremely light and has no dependencies. Far easier to use than Kestrel.

**Comment by DevTKSS** [comment]
Adding link to discord server messages including problems with the above shown code
- https://discord.com/channels/1182775715242967050/1193995186951426048/1401619641171837018

- [ ] the properties in the top if-statements coming from the `Windows.Security.Authentication.Web` are beeing dropped from implemenation (`UNO001` Not Implement`) from `Uno.Sdk="6.0.146"` upwards (tested also with the latest dev build of the sdk today using `global.json` with the latest pre release nuget version and `allowPrerelease = true`)
- [ ] `IWebAuthenticationBrokerProvider` interface or more the `Uno.AuthenticationBroker` Namespace is not longer known in Apps using the `Uno App` vs2022 vsix template, **But** using a `Uno Library` project that's resolving fine.
- [ ] While `UNO_HAS_SKIA` is recognized in a `Uno App` Project using the editor context set to `net9.0-desktop` the Constant is resolving as enabled, with the before mentioned errors, but doing the same in a new created `Uno Library` Project or a regular `Class Library` with added desktop target is resolving the code sample above as disabled and for Android for example the code is enabled instead.

I tryed to put the file onto a seperate project because the uno docs for `ApiExtensionAttri ute` are introducing us, that the App Initializer will catch it up to make it available if its imported from a package, which would not be the case for a file in the app its used in per definition.

Additionaly I am not sure how we might be meant to import this shown code, because registring it via 

```csharp
ConfigureServices((context, services) =>
 services.AddSingleton<IWebAuthenticationBrokerProvider,SystemBrowserAuthBroker>()
```
(Had the file in same project at this time)
Is giving me the error message that even while I had all required namespaces in the using section, both are not known. Is there a specific point where we would need to register it instead?

**Comment by kazo0** [comment]
@carldebilly should your `SystemBrowserAuthBroker` be defined and registered via APIExtension inside of the Uno Extensions Auth library itself? 

Would this be a temporary way of handling auth until https://github.com/unoplatform/uno/issues/19787 is implemented?

I'm not sure where/how to use this IWebAuthenticationBrokerProvider implementation when using Uno Auth MSAL/OIDC Extensions

**Comment by DevTKSS** [comment]
@kazo0 I think the not supporting of https with tcp might be a problematic limitation since most external auth api that doesnt allow device code oAuth flow for example, would not accept http requests as such...

**Comment by DevTKSS** [comment]
@kazo0

1. **OidcAuthenticationProvider likely still fails on Desktop/Skia**

    Even though the `IdentityModel.OidcClient` namespace now matches the rebranded `Duende.IdentityModel.OidcClient` in the latest `Uno.Extensions`, I would still expect Desktop/Skia to fail because `OidcAuthenticationProvider` relies on: `WebAuthenticationBroker.GetCurrentApplicationCallbackUri()`

    https://github.com/unoplatform/uno.extensions/blob/523597569a4d81413a7b7e6af87d6eafb6e124f1/src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs#L16-L28

    …but `WebAuthenticationBroker` isn’t implemented on Desktop, and we also don’t have the usual csproj/Win32-manifest style “registered callback URI” support you’d know from classic WinForms/WPF frameworks. 🫤

2. **WebAuthenticationProvider hard-depends on WebAuthenticationBroker.AuthenticateAsync** `Uno.Extensions.Authentication.UI`’s `WebAuthenticationProvider` is strongly coupled to:  `WebAuthenticationBroker.AuthenticateAsync(...)`

    https://github.com/unoplatform/uno.extensions/blob/523597569a4d81413a7b7e6af87d6eafb6e124f1/src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs#L86-L93

3. **IWebAuthenticationBrokerProvider can’t be DI-resolved due to ApiExtensibility.CreateInstance**

    I tried registering my own `IWebAuthenticationBrokerProvider` via `IServiceCollection`, but it can’t be resolved
    - Tryed even if I using Custom Auth https://github.com/unoplatform/uno.extensions/issues/2895
    - with ctor dependencies because [`ApiExtensibility.CreateInstance(...)`](https://github.com/unoplatform/uno/blob/master/src/Uno.Foundation/Extensibility/ApiExtensibility.cs) bypasses DI entirely.
    So any Implementation of `WebAuthenticationBrokerProvider` that needs `IOptions<AuthOptions>` or a dedicated service (e.g., an `OAuthCallbackHandler`). This could be workaround'ed by accepting `IWebAuthenticationBrowserProvider` via optional ctor argument as suggested in my PR on the Uno.Extensions Repo: https://github.com/unoplatform/uno.extensions/pull/2890
    
4. **WebAuthenticationBroker ignores IServiceCollection registrations** because `WebAuthenticationBroker` uses `ApiExtensibility.CreateInstance(null, out _authenticationBrokerProvider);`. So even if an implementation of `IWebAuthenticationBrokerProvider` exists in DI, it won’t be used 

5. **ApiExtensibilityAttribute doesn’t support ctor args (and null likely blocks it anyway)**

    The `[ApiExtensibility(...)]` mechanism doesn’t allow passing ctor arguments, and the explicit `null` passed into `CreateInstance(...)` appears to prevent any pathway for DI-based creation.

    https://github.com/unoplatform/uno/blob/f5cc992e78fcac760f4a9dbde445306eea5aaff7/src/Uno.Foundation/Extensibility/ApiExtensibility.cs#L71-L96

6. While it would be really cool and straight forward, the Walkthrought for Web Auth in the Docs is false stating that it will be using `WebView` which is *not* the case! https://github.com/unoplatform/uno.extensions/issues/2972

---

### Why I’m bringing this up (practical integration angle)

I tried the above with the `AuthCallbackHandler` from my PR against `carldebilly/Yllibed.HttpServer`:

- https://github.com/carldebilly/Yllibed.HttpServer/pull/12

This handler could act (at least in Development) as the local OAuth callback backend for Uno apps eventually even for the [currently ***not WebView using*** Web Auth as stated in the Docs](https://platform.uno/docs/articles/external/uno.extensions/doc/Learn/Walkthrough/Authentication.Web.howto.html#breadcrumb)

It’s possible to integrate cleanly, with (or without) support of `IOptions<T>`, comes with tests, and includes a dedicated integration path for [`WebAuthenticationResult`](https://github.com/unoplatform/uno/blob/77c6ca0533a63be48c6bbdd830c8653e17a9b0fa/src/Uno.UWP/Security/Authentication/Web/WebAuthenticationResult.cs) - which `WebAuthenticationProvider` currently expects from `WebAuthenticationBroker`.


**But** due to (4) + (5), there’s currently no workable way to integrate such a provider into the existing `Uno.Extensions.Authentication` flow on Desktop/Skia.

@Jen-Uno FYI - Maybe you could take a look if there is some progress available for this? Merging the PR to allow a DI version of the `IWebAuthenticationBrokerProvider` in the `WebAuthenticationProvider` would from my POV be the lowest effort option to have a working Desktop Auth Workaround until someone comes up with a other / better solution 👍

**Comment by kazo0** [comment]
**Re-scoping this issue to OIDC/Web — dropping MSAL from its scope.**

MSAL no longer needs a `WebAuthenticationBroker` on Desktop/Skia:

- `MsalAuthenticationProvider` never uses the WAB on desktop targets — MSAL.NET drives interactive sign-in itself via the system browser + loopback redirect (`http://localhost`). The provider's only WAB call (`WithWebRedirectUri()`) is gated to WebAssembly, where the broker has a working implementation.
- With unoplatform/uno#24055 (the fix for unoplatform/uno#20601, wrong `Uno.UI.MSAL` flavor deployed under `UnoFeatures=SkiaRenderer`), interactive MSAL sign-in was validated live on Skia-Desktop (system browser + loopback), Skia-Android (custom tab), and Skia-WASM (popup via `WasmWebUi`).

What remains — and why this issue stays open:

- `OidcAuthenticationProvider` drives its browser through `WebAuthenticatorBrowser`, which wraps `WebAuthenticationBroker.AuthenticateAsync`.
- The generic `WebAuthenticationProvider` (`AddWeb`) calls `WebAuthenticationBroker.AuthenticateAsync` directly.
- Uno's default Skia broker (`WebAuthenticationBrokerProvider.skia.cs`) throws `NotImplementedException`, so both providers are non-functional on Desktop/Skia unless the app registers a custom `IWebAuthenticationBrokerProvider` (like @carldebilly's `SystemBrowserAuthBroker` above).

Open design question for whoever picks this up: a default in-Uno WAB implementation (e.g. the lightweight-HTTP-server approach above) vs. an OidcClient `IBrowser` implementation in this repo vs. aligning with WinAppSdk 1.7's `OAuth2Manager`.

Separate note: MSAL's WAM broker (`WithBroker`) is currently only wired on the WinAppSdk head; enabling WAM SSO for desktop-TFM apps running on Windows would be an MSAL enhancement independent of the WebAuthenticationBroker.
